//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;

namespace BalanzaWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BalanzaWS.BalanzaWSSoap")]
    public interface BalanzaWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdenBalanzaDocentry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.GetOrdenBalanzaDocentryResponse> GetOrdenBalanzaDocentryAsync(BalanzaWS.GetOrdenBalanzaDocentryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdenBalanza", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.GetOrdenBalanzaResponse> GetOrdenBalanzaAsync(BalanzaWS.GetOrdenBalanzaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSeries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.GetSeriesResponse> GetSeriesAsync(BalanzaWS.GetSeriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetSeries", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)] 
        System.Threading.Tasks.Task<BalanzaWS.GetEtapasResponse> GetEtapasAsync(BalanzaWS.GetEtapasRequest request);


        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMateriales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.GetMaterialesResponse> GetMaterialesAsync(BalanzaWS.GetMaterialesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUnidadesAlternativas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.GetUnidadesAlternativasResponse> GetUnidadesAlternativasAsync(BalanzaWS.GetUnidadesAlternativasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.AddSAPResponse> AddSAPAsync(BalanzaWS.AddSAPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddParteEntrega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.AddParteEntregaResponse> AddParteEntregaAsync(BalanzaWS.AddParteEntregaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCalidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.AddCalidadResponse> AddCalidadAsync(BalanzaWS.AddCalidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBalanza", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.AddBalanzaResponse> AddBalanzaAsync(BalanzaWS.AddBalanzaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBalanza", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.DeleteBalanzaResponse> DeleteBalanzaAsync(BalanzaWS.DeleteBalanzaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObservarBalanza", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.ObservarBalanzaResponse> ObservarBalanzaAsync(BalanzaWS.ObservarBalanzaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.GetPDFResponse> GetPDFAsync(BalanzaWS.GetPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEtiquetaCR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.GetEtiquetaCRResponse> GetEtiquetaCRAsync(BalanzaWS.GetEtiquetaCRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticationUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BalanzaWS.AuthenticationUserResponse> AuthenticationUserAsync(BalanzaWS.AuthenticationUserRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SecuredTokenWebservice
    {
        
        private string userNameField;
        
        private string authenticationTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AuthenticationToken
        {
            get
            {
                return this.authenticationTokenField;
            }
            set
            {
                this.authenticationTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Balanza
    {
        
        private string codigoField;
        
        private string idEmpleadoField;
        
        private int ordenFabricacionField;
        
        private string etapaField;
        
        private string maquinaField;
        
        private string codigoArticuloField;
        
        private string nombreArticuloField;
        
        private string unidadMedidaField;
        
        private string unidadAlternativaField;
        
        private double cantidadField;
        
        private double taraField;
        
        private double pesoBrutoField;
        
        private double pesoNetoField;
        
        private int numeroField;
        
        private System.DateTime fechaField;
        
        private string horaField;
        
        private int reciboProduccionField;
        
        private string tipoField;
        
        private string loteField;
        
        private string materialField;
        
        private string destinoManField;
        
        private string medidaManField;
        
        private string espesorManField;
        
        private string parteEntField;
        
        private string statusField;
        
        private string aproCalidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdEmpleado
        {
            get
            {
                return this.idEmpleadoField;
            }
            set
            {
                this.idEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int OrdenFabricacion
        {
            get
            {
                return this.ordenFabricacionField;
            }
            set
            {
                this.ordenFabricacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Etapa
        {
            get
            {
                return this.etapaField;
            }
            set
            {
                this.etapaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Maquina
        {
            get
            {
                return this.maquinaField;
            }
            set
            {
                this.maquinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CodigoArticulo
        {
            get
            {
                return this.codigoArticuloField;
            }
            set
            {
                this.codigoArticuloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NombreArticulo
        {
            get
            {
                return this.nombreArticuloField;
            }
            set
            {
                this.nombreArticuloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UnidadMedida
        {
            get
            {
                return this.unidadMedidaField;
            }
            set
            {
                this.unidadMedidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string UnidadAlternativa
        {
            get
            {
                return this.unidadAlternativaField;
            }
            set
            {
                this.unidadAlternativaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double Cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double Tara
        {
            get
            {
                return this.taraField;
            }
            set
            {
                this.taraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double PesoBruto
        {
            get
            {
                return this.pesoBrutoField;
            }
            set
            {
                this.pesoBrutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double PesoNeto
        {
            get
            {
                return this.pesoNetoField;
            }
            set
            {
                this.pesoNetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime Fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Hora
        {
            get
            {
                return this.horaField;
            }
            set
            {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int ReciboProduccion
        {
            get
            {
                return this.reciboProduccionField;
            }
            set
            {
                this.reciboProduccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Lote
        {
            get
            {
                return this.loteField;
            }
            set
            {
                this.loteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Material
        {
            get
            {
                return this.materialField;
            }
            set
            {
                this.materialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string DestinoMan
        {
            get
            {
                return this.destinoManField;
            }
            set
            {
                this.destinoManField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string MedidaMan
        {
            get
            {
                return this.medidaManField;
            }
            set
            {
                this.medidaManField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string EspesorMan
        {
            get
            {
                return this.espesorManField;
            }
            set
            {
                this.espesorManField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string ParteEnt
        {
            get
            {
                return this.parteEntField;
            }
            set
            {
                this.parteEntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string AproCalidad
        {
            get
            {
                return this.aproCalidadField;
            }
            set
            {
                this.aproCalidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultadoBalanza
    {
        
        private string codeField;
        
        private string errCodeField;
        
        private string errMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrCode
        {
            get
            {
                return this.errCodeField;
            }
            set
            {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrMsg
        {
            get
            {
                return this.errMsgField;
            }
            set
            {
                this.errMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultadoReciboProduccion
    {
        
        private string codeField;
        
        private string errCodeField;
        
        private string errMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrCode
        {
            get
            {
                return this.errCodeField;
            }
            set
            {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrMsg
        {
            get
            {
                return this.errMsgField;
            }
            set
            {
                this.errMsgField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrdenBalanzaDocentry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrdenBalanzaDocentryRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nroOrden;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string idUser;
        
        public GetOrdenBalanzaDocentryRequest()
        {
        }
        
        public GetOrdenBalanzaDocentryRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string nroOrden, string idUser)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.nroOrden = nroOrden;
            this.idUser = idUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrdenBalanzaDocentryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrdenBalanzaDocentryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetOrdenBalanzaDocentryResult;
        
        public GetOrdenBalanzaDocentryResponse()
        {
        }
        
        public GetOrdenBalanzaDocentryResponse(string GetOrdenBalanzaDocentryResult)
        {
            this.GetOrdenBalanzaDocentryResult = GetOrdenBalanzaDocentryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrdenBalanza", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrdenBalanzaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string IdSerie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string DocNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string idUser;
        
        public GetOrdenBalanzaRequest()
        {
        }
        
        public GetOrdenBalanzaRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string IdSerie, string DocNum, string idUser)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.IdSerie = IdSerie;
            this.DocNum = DocNum;
            this.idUser = idUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrdenBalanzaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrdenBalanzaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetOrdenBalanzaResult;
        
        public GetOrdenBalanzaResponse()
        {
        }
        
        public GetOrdenBalanzaResponse(string GetOrdenBalanzaResult)
        {
            this.GetOrdenBalanzaResult = GetOrdenBalanzaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSeries", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSeriesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        public GetSeriesRequest()
        {
        }
        
        public GetSeriesRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
        }
    }
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetSeriesResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetSeriesResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public string GetSeriesResult;

        public GetSeriesResponse()
        {
        }

        public GetSeriesResponse(string GetSeriesResult)
        {
            this.GetSeriesResult = GetSeriesResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEtapas", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEtapasRequest
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;

        public GetEtapasRequest()
        {
        }

        public GetEtapasRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEtapasResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEtapasResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public string GetEtapasResult;

        public GetEtapasResponse()
        {
        }

        public GetEtapasResponse(string GetEtapasResult)
        {
            this.GetEtapasResult = GetEtapasResult;
        }
    }


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMateriales", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMaterialesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        public GetMaterialesRequest()
        {
        }
        
        public GetMaterialesRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMaterialesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMaterialesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetMaterialesResult;
        
        public GetMaterialesResponse()
        {
        }
        
        public GetMaterialesResponse(string GetMaterialesResult)
        {
            this.GetMaterialesResult = GetMaterialesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUnidadesAlternativas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUnidadesAlternativasRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        public GetUnidadesAlternativasRequest()
        {
        }
        
        public GetUnidadesAlternativasRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUnidadesAlternativasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUnidadesAlternativasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetUnidadesAlternativasResult;
        
        public GetUnidadesAlternativasResponse()
        {
        }
        
        public GetUnidadesAlternativasResponse(string GetUnidadesAlternativasResult)
        {
            this.GetUnidadesAlternativasResult = GetUnidadesAlternativasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddSAP", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddSAPRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CodBalanza;
        
        public AddSAPRequest()
        {
        }
        
        public AddSAPRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string CodBalanza)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.CodBalanza = CodBalanza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddSAPResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddSAPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BalanzaWS.ResultadoReciboProduccion AddSAPResult;
        
        public AddSAPResponse()
        {
        }
        
        public AddSAPResponse(BalanzaWS.ResultadoReciboProduccion AddSAPResult)
        {
            this.AddSAPResult = AddSAPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddParteEntrega", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddParteEntregaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CodBalanza;
        
        public AddParteEntregaRequest()
        {
        }
        
        public AddParteEntregaRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string CodBalanza)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.CodBalanza = CodBalanza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddParteEntregaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddParteEntregaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BalanzaWS.ResultadoBalanza AddParteEntregaResult;
        
        public AddParteEntregaResponse()
        {
        }
        
        public AddParteEntregaResponse(BalanzaWS.ResultadoBalanza AddParteEntregaResult)
        {
            this.AddParteEntregaResult = AddParteEntregaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCalidad", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCalidadRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CodBalanza;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string User;
        
        public AddCalidadRequest()
        {
        }
        
        public AddCalidadRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string CodBalanza, string User)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.CodBalanza = CodBalanza;
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCalidadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCalidadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BalanzaWS.ResultadoBalanza AddCalidadResult;
        
        public AddCalidadResponse()
        {
        }
        
        public AddCalidadResponse(BalanzaWS.ResultadoBalanza AddCalidadResult)
        {
            this.AddCalidadResult = AddCalidadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddBalanza", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddBalanzaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BalanzaWS.Balanza balanzaReg;
        
        public AddBalanzaRequest()
        {
        }
        
        public AddBalanzaRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, BalanzaWS.Balanza balanzaReg)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.balanzaReg = balanzaReg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddBalanzaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddBalanzaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BalanzaWS.ResultadoBalanza AddBalanzaResult;
        
        public AddBalanzaResponse()
        {
        }
        
        public AddBalanzaResponse(BalanzaWS.ResultadoBalanza AddBalanzaResult)
        {
            this.AddBalanzaResult = AddBalanzaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteBalanza", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteBalanzaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Codigo;
        
        public DeleteBalanzaRequest()
        {
        }
        
        public DeleteBalanzaRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string Codigo)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.Codigo = Codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteBalanzaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteBalanzaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BalanzaWS.ResultadoBalanza DeleteBalanzaResult;
        
        public DeleteBalanzaResponse()
        {
        }
        
        public DeleteBalanzaResponse(BalanzaWS.ResultadoBalanza DeleteBalanzaResult)
        {
            this.DeleteBalanzaResult = DeleteBalanzaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObservarBalanza", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObservarBalanzaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Codigo;
        
        public ObservarBalanzaRequest()
        {
        }
        
        public ObservarBalanzaRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string Codigo)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.Codigo = Codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObservarBalanzaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObservarBalanzaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BalanzaWS.ResultadoBalanza ObservarBalanzaResult;
        
        public ObservarBalanzaResponse()
        {
        }
        
        public ObservarBalanzaResponse(BalanzaWS.ResultadoBalanza ObservarBalanzaResult)
        {
            this.ObservarBalanzaResult = ObservarBalanzaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPDF", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPDFRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Codigo;
        
        public GetPDFRequest()
        {
        }
        
        public GetPDFRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string Codigo)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.Codigo = Codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPDFResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetPDFResult;
        
        public GetPDFResponse()
        {
        }
        
        public GetPDFResponse(string GetPDFResult)
        {
            this.GetPDFResult = GetPDFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEtiquetaCR", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEtiquetaCRRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string tipo;
        
        public GetEtiquetaCRRequest()
        {
        }
        
        public GetEtiquetaCRRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string Codigo, string tipo)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.Codigo = Codigo;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEtiquetaCRResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEtiquetaCRResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetEtiquetaCRResult;
        
        public GetEtiquetaCRResponse()
        {
        }
        
        public GetEtiquetaCRResponse(string GetEtiquetaCRResult)
        {
            this.GetEtiquetaCRResult = GetEtiquetaCRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticationUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticationUserRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        public AuthenticationUserRequest()
        {
        }
        
        public AuthenticationUserRequest(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticationUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticationUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AuthenticationUserResult;
        
        public AuthenticationUserResponse()
        {
        }
        
        public AuthenticationUserResponse(string AuthenticationUserResult)
        {
            this.AuthenticationUserResult = AuthenticationUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface BalanzaWSSoapChannel : BalanzaWS.BalanzaWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class BalanzaWSSoapClient : System.ServiceModel.ClientBase<BalanzaWS.BalanzaWSSoap>, BalanzaWS.BalanzaWSSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BalanzaWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BalanzaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), BalanzaWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BalanzaWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BalanzaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BalanzaWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BalanzaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BalanzaWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.GetOrdenBalanzaDocentryResponse> BalanzaWS.BalanzaWSSoap.GetOrdenBalanzaDocentryAsync(BalanzaWS.GetOrdenBalanzaDocentryRequest request)
        {
            return base.Channel.GetOrdenBalanzaDocentryAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.GetOrdenBalanzaDocentryResponse> GetOrdenBalanzaDocentryAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string nroOrden, string idUser)
        {
            BalanzaWS.GetOrdenBalanzaDocentryRequest inValue = new BalanzaWS.GetOrdenBalanzaDocentryRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.nroOrden = nroOrden;
            inValue.idUser = idUser;
            return ((BalanzaWS.BalanzaWSSoap)(this)).GetOrdenBalanzaDocentryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.GetOrdenBalanzaResponse> BalanzaWS.BalanzaWSSoap.GetOrdenBalanzaAsync(BalanzaWS.GetOrdenBalanzaRequest request)
        {
            return base.Channel.GetOrdenBalanzaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.GetOrdenBalanzaResponse> GetOrdenBalanzaAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string IdSerie, string DocNum, string idUser)
        {
            BalanzaWS.GetOrdenBalanzaRequest inValue = new BalanzaWS.GetOrdenBalanzaRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.IdSerie = IdSerie;
            inValue.DocNum = DocNum;
            inValue.idUser = idUser;
            return ((BalanzaWS.BalanzaWSSoap)(this)).GetOrdenBalanzaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.GetSeriesResponse> BalanzaWS.BalanzaWSSoap.GetSeriesAsync(BalanzaWS.GetSeriesRequest request)
        {
            return base.Channel.GetSeriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.GetSeriesResponse> GetSeriesAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            BalanzaWS.GetSeriesRequest inValue = new BalanzaWS.GetSeriesRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            return ((BalanzaWS.BalanzaWSSoap)(this)).GetSeriesAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.GetEtapasResponse> BalanzaWS.BalanzaWSSoap.GetEtapasAsync(BalanzaWS.GetEtapasRequest request)
        {
            return base.Channel.GetEtapasAsync(request);
        }
        public System.Threading.Tasks.Task<BalanzaWS.GetEtapasResponse> GetEtapasAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            BalanzaWS.GetEtapasRequest inValue = new BalanzaWS.GetEtapasRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            return ((BalanzaWS.BalanzaWSSoap)(this)).GetEtapasAsync(inValue);
        }


        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.GetMaterialesResponse> BalanzaWS.BalanzaWSSoap.GetMaterialesAsync(BalanzaWS.GetMaterialesRequest request)
        {
            return base.Channel.GetMaterialesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.GetMaterialesResponse> GetMaterialesAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            BalanzaWS.GetMaterialesRequest inValue = new BalanzaWS.GetMaterialesRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            return ((BalanzaWS.BalanzaWSSoap)(this)).GetMaterialesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.GetUnidadesAlternativasResponse> BalanzaWS.BalanzaWSSoap.GetUnidadesAlternativasAsync(BalanzaWS.GetUnidadesAlternativasRequest request)
        {
            return base.Channel.GetUnidadesAlternativasAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.GetUnidadesAlternativasResponse> GetUnidadesAlternativasAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            BalanzaWS.GetUnidadesAlternativasRequest inValue = new BalanzaWS.GetUnidadesAlternativasRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            return ((BalanzaWS.BalanzaWSSoap)(this)).GetUnidadesAlternativasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.AddSAPResponse> BalanzaWS.BalanzaWSSoap.AddSAPAsync(BalanzaWS.AddSAPRequest request)
        {
            return base.Channel.AddSAPAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.AddSAPResponse> AddSAPAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string CodBalanza)
        {
            BalanzaWS.AddSAPRequest inValue = new BalanzaWS.AddSAPRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.CodBalanza = CodBalanza;
            return ((BalanzaWS.BalanzaWSSoap)(this)).AddSAPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.AddParteEntregaResponse> BalanzaWS.BalanzaWSSoap.AddParteEntregaAsync(BalanzaWS.AddParteEntregaRequest request)
        {
            return base.Channel.AddParteEntregaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.AddParteEntregaResponse> AddParteEntregaAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string CodBalanza)
        {
            BalanzaWS.AddParteEntregaRequest inValue = new BalanzaWS.AddParteEntregaRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.CodBalanza = CodBalanza;
            return ((BalanzaWS.BalanzaWSSoap)(this)).AddParteEntregaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.AddCalidadResponse> BalanzaWS.BalanzaWSSoap.AddCalidadAsync(BalanzaWS.AddCalidadRequest request)
        {
            return base.Channel.AddCalidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.AddCalidadResponse> AddCalidadAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string CodBalanza, string User)
        {
            BalanzaWS.AddCalidadRequest inValue = new BalanzaWS.AddCalidadRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.CodBalanza = CodBalanza;
            inValue.User = User;
            return ((BalanzaWS.BalanzaWSSoap)(this)).AddCalidadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.AddBalanzaResponse> BalanzaWS.BalanzaWSSoap.AddBalanzaAsync(BalanzaWS.AddBalanzaRequest request)
        {
            return base.Channel.AddBalanzaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.AddBalanzaResponse> AddBalanzaAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, BalanzaWS.Balanza balanzaReg)
        {
            BalanzaWS.AddBalanzaRequest inValue = new BalanzaWS.AddBalanzaRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.balanzaReg = balanzaReg;
            return ((BalanzaWS.BalanzaWSSoap)(this)).AddBalanzaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.DeleteBalanzaResponse> BalanzaWS.BalanzaWSSoap.DeleteBalanzaAsync(BalanzaWS.DeleteBalanzaRequest request)
        {
            return base.Channel.DeleteBalanzaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.DeleteBalanzaResponse> DeleteBalanzaAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string Codigo)
        {
            BalanzaWS.DeleteBalanzaRequest inValue = new BalanzaWS.DeleteBalanzaRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.Codigo = Codigo;
            return ((BalanzaWS.BalanzaWSSoap)(this)).DeleteBalanzaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.ObservarBalanzaResponse> BalanzaWS.BalanzaWSSoap.ObservarBalanzaAsync(BalanzaWS.ObservarBalanzaRequest request)
        {
            return base.Channel.ObservarBalanzaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.ObservarBalanzaResponse> ObservarBalanzaAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string Codigo)
        {
            BalanzaWS.ObservarBalanzaRequest inValue = new BalanzaWS.ObservarBalanzaRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.Codigo = Codigo;
            return ((BalanzaWS.BalanzaWSSoap)(this)).ObservarBalanzaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.GetPDFResponse> BalanzaWS.BalanzaWSSoap.GetPDFAsync(BalanzaWS.GetPDFRequest request)
        {
            return base.Channel.GetPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.GetPDFResponse> GetPDFAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string Codigo)
        {
            BalanzaWS.GetPDFRequest inValue = new BalanzaWS.GetPDFRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.Codigo = Codigo;
            return ((BalanzaWS.BalanzaWSSoap)(this)).GetPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.GetEtiquetaCRResponse> BalanzaWS.BalanzaWSSoap.GetEtiquetaCRAsync(BalanzaWS.GetEtiquetaCRRequest request)
        {
            return base.Channel.GetEtiquetaCRAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.GetEtiquetaCRResponse> GetEtiquetaCRAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice, string Codigo, string tipo)
        {
            BalanzaWS.GetEtiquetaCRRequest inValue = new BalanzaWS.GetEtiquetaCRRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.Codigo = Codigo;
            inValue.tipo = tipo;
            return ((BalanzaWS.BalanzaWSSoap)(this)).GetEtiquetaCRAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BalanzaWS.AuthenticationUserResponse> BalanzaWS.BalanzaWSSoap.AuthenticationUserAsync(BalanzaWS.AuthenticationUserRequest request)
        {
            return base.Channel.AuthenticationUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BalanzaWS.AuthenticationUserResponse> AuthenticationUserAsync(BalanzaWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            BalanzaWS.AuthenticationUserRequest inValue = new BalanzaWS.AuthenticationUserRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            return ((BalanzaWS.BalanzaWSSoap)(this)).AuthenticationUserAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BalanzaWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BalanzaWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BalanzaWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8003/BalanzaWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BalanzaWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8003/BalanzaWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }


        public enum EndpointConfiguration
        {
            
            BalanzaWSSoap,
            
            BalanzaWSSoap12,
        }
    }
}
