//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlHorasWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControlHorasWS.ControlHoraWSSoap")]
    public interface ControlHoraWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdenCtrHorasDocEntry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlHorasWS.GetOrdenCtrHorasDocEntryResponse> GetOrdenCtrHorasDocEntryAsync(ControlHorasWS.GetOrdenCtrHorasDocEntryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdenCtrHoras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlHorasWS.GetOrdenCtrHorasResponse> GetOrdenCtrHorasAsync(ControlHorasWS.GetOrdenCtrHorasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEntrega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlHorasWS.AddEntregaResponse> AddEntregaAsync(ControlHorasWS.AddEntregaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTipoParada", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlHorasWS.GetTipoParadaResponse> GetTipoParadaAsync(ControlHorasWS.GetTipoParadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDetCtrlHora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlHorasWS.GetDetCtrlHoraResponse> GetDetCtrlHoraAsync(ControlHorasWS.GetDetCtrlHoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCtrlHoraList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlHorasWS.GetCtrlHoraListResponse> GetCtrlHoraListAsync(ControlHorasWS.GetCtrlHoraListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCtrHora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlHorasWS.AddCtrHoraResponse> AddCtrHoraAsync(ControlHorasWS.AddCtrHoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPare", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlHorasWS.AddPareResponse> AddPareAsync(ControlHorasWS.AddPareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticationUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlHorasWS.AuthenticationUserResponse> AuthenticationUserAsync(ControlHorasWS.AuthenticationUserRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SecuredTokenWebservice
    {
        
        private string userNameField;
        
        private string authenticationTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AuthenticationToken
        {
            get
            {
                return this.authenticationTokenField;
            }
            set
            {
                this.authenticationTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultadoParada
    {
        
        private string codeField;
        
        private string errCodeField;
        
        private string errMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrCode
        {
            get
            {
                return this.errCodeField;
            }
            set
            {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrMsg
        {
            get
            {
                return this.errMsgField;
            }
            set
            {
                this.errMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Parada
    {
        
        private string idEmpleadoField;
        
        private int ordenFabricacionField;
        
        private string etapaField;
        
        private string recursoField;
        
        private string tipoParaField;
        
        private string tipoParaDescField;
        
        private string motivoParaField;
        
        private string tipoField;
        
        private System.DateTime fechaField;
        
        private string horaField;
        
        private string origenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdEmpleado
        {
            get
            {
                return this.idEmpleadoField;
            }
            set
            {
                this.idEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int OrdenFabricacion
        {
            get
            {
                return this.ordenFabricacionField;
            }
            set
            {
                this.ordenFabricacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Etapa
        {
            get
            {
                return this.etapaField;
            }
            set
            {
                this.etapaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Recurso
        {
            get
            {
                return this.recursoField;
            }
            set
            {
                this.recursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TipoPara
        {
            get
            {
                return this.tipoParaField;
            }
            set
            {
                this.tipoParaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TipoParaDesc
        {
            get
            {
                return this.tipoParaDescField;
            }
            set
            {
                this.tipoParaDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MotivoPara
        {
            get
            {
                return this.motivoParaField;
            }
            set
            {
                this.motivoParaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime Fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Hora
        {
            get
            {
                return this.horaField;
            }
            set
            {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Origen
        {
            get
            {
                return this.origenField;
            }
            set
            {
                this.origenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultadoControlHora
    {
        
        private string codeField;
        
        private string errCodeField;
        
        private string errMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrCode
        {
            get
            {
                return this.errCodeField;
            }
            set
            {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrMsg
        {
            get
            {
                return this.errMsgField;
            }
            set
            {
                this.errMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ControlHora
    {
        
        private string codigoField;
        
        private string idEmpleadoField;
        
        private int ordenFabricacionField;
        
        private string etapaField;
        
        private string recursoField;
        
        private string tipoField;
        
        private System.DateTime fechaField;
        
        private string horaField;
        
        private string origenField;
        
        private string estadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdEmpleado
        {
            get
            {
                return this.idEmpleadoField;
            }
            set
            {
                this.idEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int OrdenFabricacion
        {
            get
            {
                return this.ordenFabricacionField;
            }
            set
            {
                this.ordenFabricacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Etapa
        {
            get
            {
                return this.etapaField;
            }
            set
            {
                this.etapaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Recurso
        {
            get
            {
                return this.recursoField;
            }
            set
            {
                this.recursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime Fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Hora
        {
            get
            {
                return this.horaField;
            }
            set
            {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Origen
        {
            get
            {
                return this.origenField;
            }
            set
            {
                this.origenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultadoEmisionProduccion
    {
        
        private string codeField;
        
        private string errCodeField;
        
        private string errMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrCode
        {
            get
            {
                return this.errCodeField;
            }
            set
            {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrMsg
        {
            get
            {
                return this.errMsgField;
            }
            set
            {
                this.errMsgField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrdenCtrHorasDocEntry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrdenCtrHorasDocEntryRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nroOrden;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string idUser;
        
        public GetOrdenCtrHorasDocEntryRequest()
        {
        }
        
        public GetOrdenCtrHorasDocEntryRequest(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, string nroOrden, string idUser)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.nroOrden = nroOrden;
            this.idUser = idUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrdenCtrHorasDocEntryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrdenCtrHorasDocEntryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetOrdenCtrHorasDocEntryResult;
        
        public GetOrdenCtrHorasDocEntryResponse()
        {
        }
        
        public GetOrdenCtrHorasDocEntryResponse(string GetOrdenCtrHorasDocEntryResult)
        {
            this.GetOrdenCtrHorasDocEntryResult = GetOrdenCtrHorasDocEntryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrdenCtrHoras", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrdenCtrHorasRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string IdSerie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string DocNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string idUser;
        
        public GetOrdenCtrHorasRequest()
        {
        }
        
        public GetOrdenCtrHorasRequest(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, string IdSerie, string DocNum, string idUser)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.IdSerie = IdSerie;
            this.DocNum = DocNum;
            this.idUser = idUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrdenCtrHorasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrdenCtrHorasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetOrdenCtrHorasResult;
        
        public GetOrdenCtrHorasResponse()
        {
        }
        
        public GetOrdenCtrHorasResponse(string GetOrdenCtrHorasResult)
        {
            this.GetOrdenCtrHorasResult = GetOrdenCtrHorasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddEntrega", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddEntregaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CodCtrlHora;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string etapa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string maquina;
        
        public AddEntregaRequest()
        {
        }
        
        public AddEntregaRequest(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, string CodCtrlHora, string etapa, string maquina)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.CodCtrlHora = CodCtrlHora;
            this.etapa = etapa;
            this.maquina = maquina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddEntregaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddEntregaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ControlHorasWS.ResultadoEmisionProduccion AddEntregaResult;
        
        public AddEntregaResponse()
        {
        }
        
        public AddEntregaResponse(ControlHorasWS.ResultadoEmisionProduccion AddEntregaResult)
        {
            this.AddEntregaResult = AddEntregaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTipoParada", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTipoParadaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        public GetTipoParadaRequest()
        {
        }
        
        public GetTipoParadaRequest(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTipoParadaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTipoParadaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetTipoParadaResult;
        
        public GetTipoParadaResponse()
        {
        }
        
        public GetTipoParadaResponse(string GetTipoParadaResult)
        {
            this.GetTipoParadaResult = GetTipoParadaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetCtrlHora", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDetCtrlHoraRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Orden;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Etapa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string maquina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string User;
        
        public GetDetCtrlHoraRequest()
        {
        }
        
        public GetDetCtrlHoraRequest(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, int Orden, int Etapa, string maquina, string User)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.Orden = Orden;
            this.Etapa = Etapa;
            this.maquina = maquina;
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetCtrlHoraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDetCtrlHoraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDetCtrlHoraResult;
        
        public GetDetCtrlHoraResponse()
        {
        }
        
        public GetDetCtrlHoraResponse(string GetDetCtrlHoraResult)
        {
            this.GetDetCtrlHoraResult = GetDetCtrlHoraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCtrlHoraList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCtrlHoraListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string User;
        
        public GetCtrlHoraListRequest()
        {
        }
        
        public GetCtrlHoraListRequest(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, string User)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCtrlHoraListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCtrlHoraListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetCtrlHoraListResult;
        
        public GetCtrlHoraListResponse()
        {
        }
        
        public GetCtrlHoraListResponse(string GetCtrlHoraListResult)
        {
            this.GetCtrlHoraListResult = GetCtrlHoraListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCtrHora", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCtrHoraRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ControlHorasWS.ControlHora controlHoraReg;
        
        public AddCtrHoraRequest()
        {
        }
        
        public AddCtrHoraRequest(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, ControlHorasWS.ControlHora controlHoraReg)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.controlHoraReg = controlHoraReg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCtrHoraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCtrHoraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ControlHorasWS.ResultadoControlHora AddCtrHoraResult;
        
        public AddCtrHoraResponse()
        {
        }
        
        public AddCtrHoraResponse(ControlHorasWS.ResultadoControlHora AddCtrHoraResult)
        {
            this.AddCtrHoraResult = AddCtrHoraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPare", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPareRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ControlHorasWS.Parada paradaReg;
        
        public AddPareRequest()
        {
        }
        
        public AddPareRequest(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, ControlHorasWS.Parada paradaReg)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
            this.paradaReg = paradaReg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPareResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPareResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ControlHorasWS.ResultadoParada AddPareResult;
        
        public AddPareResponse()
        {
        }
        
        public AddPareResponse(ControlHorasWS.ResultadoParada AddPareResult)
        {
            this.AddPareResult = AddPareResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticationUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticationUserRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice;
        
        public AuthenticationUserRequest()
        {
        }
        
        public AuthenticationUserRequest(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            this.SecuredTokenWebservice = SecuredTokenWebservice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticationUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticationUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AuthenticationUserResult;
        
        public AuthenticationUserResponse()
        {
        }
        
        public AuthenticationUserResponse(string AuthenticationUserResult)
        {
            this.AuthenticationUserResult = AuthenticationUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ControlHoraWSSoapChannel : ControlHorasWS.ControlHoraWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ControlHoraWSSoapClient : System.ServiceModel.ClientBase<ControlHorasWS.ControlHoraWSSoap>, ControlHorasWS.ControlHoraWSSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ControlHoraWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ControlHoraWSSoapClient.GetBindingForEndpoint(endpointConfiguration), ControlHoraWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControlHoraWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ControlHoraWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControlHoraWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ControlHoraWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControlHoraWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlHorasWS.GetOrdenCtrHorasDocEntryResponse> ControlHorasWS.ControlHoraWSSoap.GetOrdenCtrHorasDocEntryAsync(ControlHorasWS.GetOrdenCtrHorasDocEntryRequest request)
        {
            return base.Channel.GetOrdenCtrHorasDocEntryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlHorasWS.GetOrdenCtrHorasDocEntryResponse> GetOrdenCtrHorasDocEntryAsync(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, string nroOrden, string idUser)
        {
            ControlHorasWS.GetOrdenCtrHorasDocEntryRequest inValue = new ControlHorasWS.GetOrdenCtrHorasDocEntryRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.nroOrden = nroOrden;
            inValue.idUser = idUser;
            return ((ControlHorasWS.ControlHoraWSSoap)(this)).GetOrdenCtrHorasDocEntryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlHorasWS.GetOrdenCtrHorasResponse> ControlHorasWS.ControlHoraWSSoap.GetOrdenCtrHorasAsync(ControlHorasWS.GetOrdenCtrHorasRequest request)
        {
            return base.Channel.GetOrdenCtrHorasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlHorasWS.GetOrdenCtrHorasResponse> GetOrdenCtrHorasAsync(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, string IdSerie, string DocNum, string idUser)
        {
            ControlHorasWS.GetOrdenCtrHorasRequest inValue = new ControlHorasWS.GetOrdenCtrHorasRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.IdSerie = IdSerie;
            inValue.DocNum = DocNum;
            inValue.idUser = idUser;
            return ((ControlHorasWS.ControlHoraWSSoap)(this)).GetOrdenCtrHorasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlHorasWS.AddEntregaResponse> ControlHorasWS.ControlHoraWSSoap.AddEntregaAsync(ControlHorasWS.AddEntregaRequest request)
        {
            return base.Channel.AddEntregaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlHorasWS.AddEntregaResponse> AddEntregaAsync(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, string CodCtrlHora, string etapa, string maquina)
        {
            ControlHorasWS.AddEntregaRequest inValue = new ControlHorasWS.AddEntregaRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.CodCtrlHora = CodCtrlHora;
            inValue.etapa = etapa;
            inValue.maquina = maquina;
            return ((ControlHorasWS.ControlHoraWSSoap)(this)).AddEntregaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlHorasWS.GetTipoParadaResponse> ControlHorasWS.ControlHoraWSSoap.GetTipoParadaAsync(ControlHorasWS.GetTipoParadaRequest request)
        {
            return base.Channel.GetTipoParadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlHorasWS.GetTipoParadaResponse> GetTipoParadaAsync(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            ControlHorasWS.GetTipoParadaRequest inValue = new ControlHorasWS.GetTipoParadaRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            return ((ControlHorasWS.ControlHoraWSSoap)(this)).GetTipoParadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlHorasWS.GetDetCtrlHoraResponse> ControlHorasWS.ControlHoraWSSoap.GetDetCtrlHoraAsync(ControlHorasWS.GetDetCtrlHoraRequest request)
        {
            return base.Channel.GetDetCtrlHoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlHorasWS.GetDetCtrlHoraResponse> GetDetCtrlHoraAsync(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, int Orden, int Etapa, string maquina, string User)
        {
            ControlHorasWS.GetDetCtrlHoraRequest inValue = new ControlHorasWS.GetDetCtrlHoraRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.Orden = Orden;
            inValue.Etapa = Etapa;
            inValue.maquina = maquina;
            inValue.User = User;
            return ((ControlHorasWS.ControlHoraWSSoap)(this)).GetDetCtrlHoraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlHorasWS.GetCtrlHoraListResponse> ControlHorasWS.ControlHoraWSSoap.GetCtrlHoraListAsync(ControlHorasWS.GetCtrlHoraListRequest request)
        {
            return base.Channel.GetCtrlHoraListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlHorasWS.GetCtrlHoraListResponse> GetCtrlHoraListAsync(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, string User)
        {
            ControlHorasWS.GetCtrlHoraListRequest inValue = new ControlHorasWS.GetCtrlHoraListRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.User = User;
            return ((ControlHorasWS.ControlHoraWSSoap)(this)).GetCtrlHoraListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlHorasWS.AddCtrHoraResponse> ControlHorasWS.ControlHoraWSSoap.AddCtrHoraAsync(ControlHorasWS.AddCtrHoraRequest request)
        {
            return base.Channel.AddCtrHoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlHorasWS.AddCtrHoraResponse> AddCtrHoraAsync(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, ControlHorasWS.ControlHora controlHoraReg)
        {
            ControlHorasWS.AddCtrHoraRequest inValue = new ControlHorasWS.AddCtrHoraRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.controlHoraReg = controlHoraReg;
            return ((ControlHorasWS.ControlHoraWSSoap)(this)).AddCtrHoraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlHorasWS.AddPareResponse> ControlHorasWS.ControlHoraWSSoap.AddPareAsync(ControlHorasWS.AddPareRequest request)
        {
            return base.Channel.AddPareAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlHorasWS.AddPareResponse> AddPareAsync(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice, ControlHorasWS.Parada paradaReg)
        {
            ControlHorasWS.AddPareRequest inValue = new ControlHorasWS.AddPareRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            inValue.paradaReg = paradaReg;
            return ((ControlHorasWS.ControlHoraWSSoap)(this)).AddPareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlHorasWS.AuthenticationUserResponse> ControlHorasWS.ControlHoraWSSoap.AuthenticationUserAsync(ControlHorasWS.AuthenticationUserRequest request)
        {
            return base.Channel.AuthenticationUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlHorasWS.AuthenticationUserResponse> AuthenticationUserAsync(ControlHorasWS.SecuredTokenWebservice SecuredTokenWebservice)
        {
            ControlHorasWS.AuthenticationUserRequest inValue = new ControlHorasWS.AuthenticationUserRequest();
            inValue.SecuredTokenWebservice = SecuredTokenWebservice;
            return ((ControlHorasWS.ControlHoraWSSoap)(this)).AuthenticationUserAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ControlHoraWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ControlHoraWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ControlHoraWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8003/ControlHoraWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ControlHoraWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8003/ControlHoraWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ControlHoraWSSoap,
            
            ControlHoraWSSoap12,
        }
    }
}
